before:
  hooks:
    - echo "[Before hook] CGO_ENABLED=$CGO_ENABLED"
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -X github.com/pulumi/crd2pulumi/gen.Version={{.Tag}}
    goarch:
      - amd64
      - arm64
    binary: crd2pulumi
    main: ./main.go
    hooks:
      pre:
        - echo "[Build pre hook] CGO_ENABLED=$CGO_ENABLED"
archives:
  - name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
brews:
  -
    name: crd2pulumi
    tap:
      owner: pulumi
      name: homebrew-tap
    commit_author:
      name: pulumi-bot
      email: bot@pulumi.com
    homepage: "https://pulumi.com"
    description: "Generate typed CustomResources in Pulumi from Kubernetes CRDs"
    folder: Formula
    license: Apache-2.0
    test: |
      system "#{bin}/crd2pulumi version"
